"""Add Address and link to Office

Revision ID: 315db8fb4762
Revises: c05bdd178642
Create Date: 2026-07-08 16:36:31.710512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '315db8fb4762'
down_revision: Union[str, Sequence[str], None] = 'c05bdd178642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('house_number', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_addresses')
    )
    op.add_column('office_history', sa.Column('address_snapshot', sa.String(), nullable=True))
    op.add_column('offices', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('offices', sa.Column('address_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_offices_address_id_addresses', 'offices', 'addresses', ['address_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_offices_address_id_addresses', 'offices', type_='foreignkey')
    op.drop_column('offices', 'address_id')
    op.drop_column('offices', 'deactivated_at')
    op.drop_column('office_history', 'address_snapshot')
    op.drop_table('addresses')
    # ### end Alembic commands ###
