"""remove_partial_index_for_office_name

Revision ID: 65ec6cbfc19c
Revises: ea842f8aa05f
Create Date: 2026-07-09 02:53:25.100834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ec6cbfc19c'
down_revision: Union[str, Sequence[str], None] = 'ea842f8aa05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_unique_active_office_name'), table_name='offices', postgresql_where='(is_active = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_unique_active_office_name'), 'offices', ['name'], unique=True, postgresql_where='(is_active = true)')
    # ### end Alembic commands ###
