"""Add description to Office models

Revision ID: c05bdd178642
Revises: fb9160d80f47
Create Date: 2026-07-08 05:26:56.113046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c05bdd178642'
down_revision: Union[str, Sequence[str], None] = 'fb9160d80f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office_history', sa.Column('description', sa.String(), nullable=True))
    op.add_column('offices', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offices', 'description')
    op.drop_column('office_history', 'description')
    # ### end Alembic commands ###
