"""Add User and Office tables

Revision ID: ed9a5d1d3828
Revises:
Create Date: 2026-07-07 01:30:37.003612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed9a5d1d3828'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_offices'),
    sa.UniqueConstraint('name', name='offices_name_key')
    )
    op.create_table('office_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('office_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('change_reason', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], name='fk_office_history_office_id_offices'),
    sa.PrimaryKeyConstraint('id', name='pk_office_history')
    )
    op.create_index(op.f('ix_office_history_office_id'), 'office_history', ['office_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'DISPATCHER', 'OFFICER', 'MANAGER', 'ADMIN', name='role'), nullable=True),
    sa.Column('office_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], name='fk_users_office_id_offices'),
    sa.PrimaryKeyConstraint('id', name='pk_users')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('CITIZEN', 'DISPATCHER', 'OFFICER', 'MANAGER', 'ADMIN', name='role'), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('change_reason', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_history_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_user_history')
    )
    op.create_index(op.f('ix_user_history_user_id'), 'user_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_history_user_id'), table_name='user_history')
    op.drop_table('user_history')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_office_history_office_id'), table_name='office_history')
    op.drop_table('office_history')
    op.drop_table('offices')
    # ### end Alembic commands ###
