"""Some changes

Revision ID: fb3008404a5a
Revises: 315db8fb4762
Create Date: 2026-07-08 23:39:45.487972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb3008404a5a'
down_revision: Union[str, Sequence[str], None] = '315db8fb4762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office_history', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('office_history', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('office_history', sa.Column('services', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('office_history', sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('offices', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('offices', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('offices', sa.Column('services', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('offices', sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offices', 'opening_hours')
    op.drop_column('offices', 'services')
    op.drop_column('offices', 'phone')
    op.drop_column('offices', 'contact_email')
    op.drop_column('office_history', 'opening_hours')
    op.drop_column('office_history', 'services')
    op.drop_column('office_history', 'phone')
    op.drop_column('office_history', 'contact_email')
    # ### end Alembic commands ###
