"""Add deactivated_at

Revision ID: fdb0684b596d
Revises: 76d8c7f82c01
Create Date: 2026-07-08 02:06:30.463117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb0684b596d'
down_revision: Union[str, Sequence[str], None] = '76d8c7f82c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deactivated_at')
    # ### end Alembic commands ###
