"""Enumerations used by the ticket aggregate and API."""

import enum

class TicketCategory(str, enum.Enum):
  """Categories retained from the previous Ktor ticket API."""

  INFRASTRUCTURE = "INFRASTRUCTURE"
  CLEANING = "CLEANING"
  SAFETY = "SAFETY"
  NOISE = "NOISE"
  OTHER = "OTHER"


class TicketVisibility(str, enum.Enum):
  """Controls whether a ticket is visible in the public community list."""

  PUBLIC = "PUBLIC"
  PRIVATE = "PRIVATE"


class TicketStatus(str, enum.Enum):
  """Coarse processing status that may be exposed to citizens."""

  OPEN = "OPEN"
  IN_PROGRESS = "IN_PROGRESS"
  RESOLVED = "RESOLVED"
  REJECTED = "REJECTED"
  CANCELLED = "CANCELLED"


class TicketWorkflowState(str, enum.Enum):
  """Internal workflow state used by the administrative client."""

  NEW = "NEW"
  AWAITING_PRIMARY_ASSIGNMENT = "AWAITING_PRIMARY_ASSIGNMENT"
  IN_PROGRESS = "IN_PROGRESS"
  WAITING_FOR_CITIZEN = "WAITING_FOR_CITIZEN"
  WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
  COMPLETED = "COMPLETED"


class TicketEventType(str, enum.Enum):
  """All event types anticipated by the first workflow iteration."""

  TICKET_SUBMITTED = "TICKET_SUBMITTED"
  TICKET_DETAILS_UPDATED = "TICKET_DETAILS_UPDATED"
  TICKET_CANCELLED = "TICKET_CANCELLED"
  TICKET_DISPATCHED = "TICKET_DISPATCHED"
  PRIMARY_OFFICER_ASSIGNED = "PRIMARY_OFFICER_ASSIGNED"
  TICKET_FORWARDED = "TICKET_FORWARDED"
  PARALLEL_WORK_ITEMS_REQUESTED = "PARALLEL_WORK_ITEMS_REQUESTED"
  WORK_ITEM_COMPLETED = "WORK_ITEM_COMPLETED"
  WORK_ITEM_CANCELLED = "WORK_ITEM_CANCELLED"
  CITIZEN_RESPONSE_REQUESTED = "CITIZEN_RESPONSE_REQUESTED"
  CITIZEN_RESPONDED = "CITIZEN_RESPONDED"
  TICKET_ESCALATED = "TICKET_ESCALATED"
  ESCALATION_APPROVED = "ESCALATION_APPROVED"
  ESCALATION_REJECTED = "ESCALATION_REJECTED"
  TICKET_RESOLVED = "TICKET_RESOLVED"
  TICKET_REJECTED = "TICKET_REJECTED"
  TICKET_COMMENTED = "TICKET_COMMENTED"
  TICKET_IMAGE_ADDED = "TICKET_IMAGE_ADDED"
  TICKET_IMAGE_REMOVED = "TICKET_IMAGE_REMOVED"
  TICKET_COVER_IMAGE_CHANGED = "TICKET_COVER_IMAGE_CHANGED"


class TicketWorkItemKind(str, enum.Enum):
  """A small set of parallel subtasks supported by the workflow."""

  COSIGNATURE = "COSIGNATURE"
  CONSULTATION = "CONSULTATION"
  APPROVAL = "APPROVAL"


class TicketWorkItemStatus(str, enum.Enum):
  """Lifecycle of a projected workflow work item."""

  OPEN = "OPEN"
  COMPLETED = "COMPLETED"
  CANCELLED = "CANCELLED"


class TicketWorkItemOutcome(str, enum.Enum):
  """Possible results of a completed review task."""

  APPROVED = "APPROVED"
  REJECTED = "REJECTED"
  ACKNOWLEDGED = "ACKNOWLEDGED"


class TicketWorkflowAction(str, enum.Enum):
  """Workflow commands currently exposed by the administrative API."""

  DISPATCH = "DISPATCH"
  ASSIGN_PRIMARY_OFFICER = "ASSIGN_PRIMARY_OFFICER"
  REQUEST_PARALLEL_COSIGNATURES = "REQUEST_PARALLEL_COSIGNATURES"
  COMPLETE_WORK_ITEM = "COMPLETE_WORK_ITEM"
  CANCEL_WORK_ITEM = "CANCEL_WORK_ITEM"
  FORWARD = "FORWARD"
  ESCALATE = "ESCALATE"
  APPROVE_ESCALATION = "APPROVE_ESCALATION"
  REJECT_ESCALATION = "REJECT_ESCALATION"
  REQUEST_CITIZEN_RESPONSE = "REQUEST_CITIZEN_RESPONSE"
  RESOLVE = "RESOLVE"
  REJECT_TICKET = "REJECT_TICKET"
